//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace authorifilter.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    public partial class USERINFO
    {
        public long RID { get; set; }
        [Required(ErrorMessage ="Username is Required.")]
        [DisplayName("Username")]
        public string USERNAME { get; set; }
        [Required(ErrorMessage ="Password is Required")]
        [DisplayName("Password")]
        public string PWD { get; set; }
    }
}
