//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ajaxform.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EMP
    {
        public long RID { get; set; }
        public string FIRSTNAME { get; set; }
        public string LASTNAME { get; set; }
        public string EMPCODE { get; set; }
        public string POSITION { get; set; }
        public string OFFICE { get; set; }
    }
}
